version: '3'

services:
  nodejs:
    build: .
    ports:
      - "5642:5642"
    networks:
      - app-network
    command: node index.js
  db:
    image: mongo:4.2
    container_name: mongo
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network
    
networks:
  app-network:
  
volumes:
  dbdata:
